# Generated by Django 2.0.6 on 2018-06-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('art', models.CharField(max_length=255)),
                ('movies', models.CharField(max_length=255)),
                ('music', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='basic_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BasicInfo'),
        ),
    ]
