# Generated by Django 2.0.6 on 2018-06-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='art',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='movies',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='music',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
